#!/usr/bin/sh

open_url(){
  # added to not rely on an xdg-utils dependency (see PR 61)
  BROWSER=($BROWSER x-www-browser quickbrowser firefox chromium chromium-browser
    brave chrome google-chrome librewolf epiphany konqueror falkon opera edge
    gnome-web vimb vieb browsh carbonyl palemoon
    com.github.Eloston.UngoogledChromium io.gitlab.librewolf-community
    org.mozilla.firefox org.chromium.Chromium com.brave.Browser
    com.opera.Opera com.google.Chrome com.microsoft.Edge dev.vieb.Vieb)

    for browser in ${BROWSER[*]}; do
      if command -v $browser &> /dev/null; then
        $browser "$1"
        exit
      fi
    done
}
 
mkdir -p $HOME/.local/share/wineland

if [ -z $WINELAND_FILE_DIR ]; then
  WINELAND_FILE_DIR="$HOME/.local/share/wineland";
fi

killall -9 wineland-civetweb

CIVETWEB=/usr/lib/wineland/wineland-civetweb
ROOT_DIR=/usr/lib/wineland/ui

if [ ! -f $CIVETWEB ]; then
  CIVETWEB=/usr/bin/civetweb
  ROOT_DIR=$PWD
fi


#for development
if [ ! -z $1 ]; then
  CIVETWEB=/usr/bin/civetweb
  ROOT_DIR=$PWD
fi

cd $ROOT_DIR

env $CIVETWEB -listening_ports 18180 -document_root $ROOT_DIR/ui \
-cgi_environment WAYLAND_DISPLAY=$WAYLAND_DISPLAY,WINELAND_FILE_DIR=$WINELAND_FILE_DIR  \
-url_rewrite_patterns \
/list-games=$ROOT_DIR/cgi/list-games.cgi\
,/launch-game=$ROOT_DIR/cgi/launch-game.cgi\
,/load-file=$ROOT_DIR/cgi/load-file.cgi\
,/save-conf=$ROOT_DIR/cgi/save-conf.cgi\
,/save-json=$ROOT_DIR/cgi/save-json.cgi\
 &

url="http://localhost:18180"
xdg-open $url
[ $? -ne 0 ] && open_url $url
