#!/usr/bin/sh

mkdir -p $HOME/.local/share/wineland

if [ -z $WINELAND_FILE_DIR ]; then
  WINELAND_FILE_DIR="$HOME/.local/share/wineland";
fi

killall -9 wineland-civetweb

CIVETWEB=/usr/lib/wineland/wineland-civetweb
ROOT_DIR=/usr/lib/wineland/ui

if [ ! -f $CIVETWEB ]; then
  CIVETWEB=/usr/bin/civetweb
  ROOT_DIR=$PWD
fi


#for development
if [ ! -z $1 ]; then
  CIVETWEB=/usr/bin/civetweb
  ROOT_DIR=$PWD
fi

cd $ROOT_DIR

env $CIVETWEB -listening_ports 18180 -document_root $ROOT_DIR/ui \
-cgi_environment WAYLAND_DISPLAY=$WAYLAND_DISPLAY,WINELAND_FILE_DIR=$WINELAND_FILE_DIR  \
-url_rewrite_patterns \
/list-games=$ROOT_DIR/cgi/list-games.cgi\
,/launch-game=$ROOT_DIR/cgi/launch-game.cgi\
,/load-file=$ROOT_DIR/cgi/load-file.cgi\
,/save-conf=$ROOT_DIR/cgi/save-conf.cgi\
,/save-json=$ROOT_DIR/cgi/save-json.cgi\
 &


xdg-open http://localhost:18180
